# src/research_crew/config/tasks.yaml
research_task:
  description: >
    Conduct thorough research on gaming company {company}. Focus on:
    1. Current company status and major game franchises
    2. Historical performance and key game releases
    3. Player demographics and engagement metrics
    4. Major challenges and opportunities in the gaming market
    5. Recent game releases, updates, and industry events
    6. Competitive landscape and market position
    7. Future outlook and upcoming game developments

    Make sure to organize your findings in a structured format with clear sections.
  expected_output: >
    A comprehensive research document with well-organized sections covering
    all the requested aspects of gaming company {company}. Include specific
    facts, figures, player metrics, and game performance data where relevant.
  agent: researcher

analysis_task:
  description: >
    Analyze the gaming industry research findings and create a comprehensive report on {company}.
    Your report should:
    1. Begin with an executive summary
    2. Include all key information from the research including game performance
    3. Provide insightful analysis of gaming trends and player behavior patterns
    4. Analyze the competitive landscape and market positioning
    5. Offer a gaming industry outlook for the company, noting that this should not be used for investment decisions
    6. Be formatted in a professional, easy-to-read style with clear headings
  expected_output: >
    A polished, professional report on gaming company {company} that presents the research
    findings with added analysis and insights about the gaming industry. The report should be
    well-structured with an executive summary, main sections, and conclusion.
  agent: analyst
  context:
    - research_task
  output_file: output/gaming_report.md